<a href="https://colab.research.google.com/github/jaeohshin/1D-random-walk/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hola I am excited to learn pytorch")

Hola I am excited to learn pytorch


In [30]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


In [3]:
## Introduction to Tensors
##
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as Python int
scalar.item()

7

In [6]:
#vector
vector = torch.tensor([7, 7, 6])
vector.ndim

1

In [7]:
vector.shape

torch.Size([3])

In [8]:
#MATRIX
MATRIX = torch.tensor([ [7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX[1]

tensor([ 9, 10])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3], 
                        [3, 6, 9],
                        [2, 4, 6]],
                       [[2, 3, 4], 
                        [4, 7, 10],
                        [3, 5, 7]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4,  6]],

        [[ 2,  3,  4],
         [ 4,  7, 10],
         [ 3,  5,  7]]])

In [12]:
TENSOR.shape

torch.Size([2, 3, 3])

In [13]:
#sec. 13 of youtubevideo

In [14]:
### Random tensors

### Random tensors

Why random tensors?

Random tensors are improtant because the way many neural networks learn is that they start with tensorsfull of random numbers and then adjust to better repreent the data.


In [15]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4177, 0.1552, 0.8011, 0.5060],
        [0.7827, 0.5365, 0.4653, 0.6538],
        [0.4538, 0.2178, 0.9042, 0.4998]])

In [16]:
random_tensor.ndim

2

In [17]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [18]:
### Zeros and ones

zeros_tensor = torch.zeros(size=(3,4))
zeros_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros_tensor*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
#Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### Create a range of tensors andtensors-like


In [27]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Tensorslike

In [28]:
ten_zeros = torch.zeros_like(input=one_to_ten)

In [29]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Element-wise multiplication

In [31]:
tensorA = torch.tensor([1, 2, 3])
tensorB = torch.tensor([3, 1, 5])
tensorA * tensorB

tensor([ 3,  2, 15])

In [32]:
torch.matmul(tensorA, tensorB)

tensor(20)